name: Update Reddit Comments

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs at midnight (00:00 UTC) every Sunday
  workflow_dispatch:  # Allows the workflow to be triggered manually

jobs:
  update_comments:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the Reddit comments fetch script
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        USER_AGENT: ${{ secrets.USER_AGENT }}
        LIMIT: ${{ secrets.LIMIT }}
        TILL_LAST_COMMENT: true
      run: |
        source .venv/bin/activate
        python fetch_comments.py

    - name: Install Pandoc
      run: sudo apt-get update && sudo apt-get install -y pandoc

    - name: Run the archive generation script
      run: |
        source .venv/bin/activate
        python generate_archive.py --type standard
        python generate_archive.py --type full
        python generate_epub.py
        python generate_site.py

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

        git add markdown_files/ven_anigha_reddit_archive_*.md epub/*.epub docs reddit_comments.db

        if git diff --cached --quiet; then
          echo "No changes to commit."
        else
          git commit -m "Update Reddit comments and markdown files"
          git push origin HEAD:${{ github.ref }}
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
